# questions.toml

# Template:
# [[questions]]
# question = "What is the answer to the question"
# answers = ["Correct Answer"]
# alternatives = ["Option 2", "Option 3", "Option n"]

[[questions]]
question = "When preparing to make a left turn from a two-way street, you should drive"
answers = ["Close to the center line"]
alternatives = ["Close to the right hand side of the road", "On the left of the center line"]

[[questions]]
question = "By looking ahead, to the sides of your vehicle and behind your vehicle as you drive, you will"
answers = ["See potential problems and become better prepared to react"]
alternatives = ["Cause neck pain", "Lose points on your driving record"]

[[questions]]
question = "A flashing yellow light means"
answers = ["Slow down and proceed with caution"]
alternatives = ["Stop and wait for directions from a police officer", "Speed up"]

[[questions]]
question = "When driving behind another vehicle on an entrance to a freeway, you should"
answers = ["Be prepared for the other vehicle to slow down"]
alternatives = ["Be prepared to enter the same gap of traffic as the other vehicle", "Not go faster than 20 mph"]

[[questions]]
question = "On an undivided highway when an emergency vehicle approaches with its siren and/or flashing lights on, you should"
answers = ["Pull to the right and stop"]
alternatives = ["Drive slowly until it has passed", "Speed up to clear traffic"]

[[questions]]
question = "If the rear of your vehicle is skidding to the left, you should"
answers = ["Turn your steering wheel to the left to correct the skid"]
alternatives = ["Not turn your steering wheel until you are through skidding", "Turn your steering wheel to the right to correct the skid"]

[[questions]]
question = "When approaching a stopped vehicle, such as a police car, tow truck, utility or maintenance vehicle, that is parked along the road and displaying flashing lights, what should you do"
answers = ["Change lanes if you safely can and slow down to a reasonable and safe speed as you pass"]
alternatives = ["Stop abruptly", "Continue as usual"]

[[questions]]
question = "According to the Iowa Implied Consent Law for both resident and nonresident drivers"
answers = ["Both of the options are true"]
alternatives = ["An arrested driver may be asked to submit to a chemical test to determine the alcohol content in his/her blood.", "Refusal to submit to chemical testing will result in the driver's driving privileges being withdrawn."]

[[questions]]
question = "You see a school bus with flashing amber (yellow) lights. What is the bus driver doing"
answers = ["Signaling to other motorists that the bus will soon be stopping to load or unload school children"]
alternatives = ["Changing gears", "Preparing to make a turn"]

[[questions]]
question = "Which of the following is a safe backing technique"
answers = ["Accelerate gently and smoothly while looking carefully behind you"]
alternatives = ["Look forward out through the windshield", "Hold the steering wheel underhanded"]

[[questions]]
question = "What should you do as you approach a curve in the road?"
answers = ["Reduce your speed before you enter the curve"]
alternatives = ["Shift your weight behind the wheel", "Put on your four-way flashers"]

[[questions]]
question = "If you are on a two-lane highway when meeting an oncoming school bus with its amber (yellow) warning lights flashing, you must"
answers = ["Slow to 20 mph and prepare to stop"]
alternatives = ["Continue as usual", "Stop at least 10 feet from the front of the bus"]

[[questions]]
question = "You are driving on a road that has two or more lanes in each direction. You meet a school bus traveling the opposite direction that is stopped with flashing red lights. Are you required to stop?"
answers = ["No, when you are approaching a stopped school bus from the opposite direction on a road that has two or more lanes in each direction, you are not required to stop and may continue carefully. This is the only time you can pass a school bus that displays flashing red lights."]
alternatives = ["Yes, you should always stop for a school bus that displays red flashing lights"]

[[questions]]
question = "Because there is often slow-moving traffic on county highways, you should"
answers = ["Be ready to change your speed to the speed of traffic"]
alternatives = ["Stay in the left lane and drive at the speed limit", "Pass slow-moving vehicles on curves if they are slowing down"]

[[questions]]
question = "When passing a vehicle, you should return to your lane when"
answers = ["You can see both its headlights in your rearview mirror"]
alternatives = ["You have cleared the front bumper of the passed vehicle", "You are 50 feet in front of the passed vehicle"]

"You are approaching an intersection and see these pavement markings. What do these pavement markings tell you" = [
    "You may make a right turn only from the right lane",
    "The two lanes will merge into one",
    "The vehicle in the right lane must turn right"
]

"Which of the below are common factors contributing to traffic crashes" = [
    "Exceeding the posted speed limit and driving too fast for conditions or circumstances",
    "Getting adequate rest and staying alert",
    "Scanning the environment and staying focused on the driving task"
]

"If you must park your vehicle in an area not usually used for parking" = [
    "Make sure your vehicle is visible to drivers approaching from either direction",
    "Park with your back-up lights on",
    "Park 5 feet from the curb"
]

"Which is the correct sequence of events as a school bus driver prepares to stop to load or unload children" = [
    "Amber lights flash at the top of the bus, the bus stops as red lights flash, a stop arm goes out and the door opens for the school children",
    "The bus driver activates red flashing lights at the top of the bus, and then activates amber flashing lights when the children are unloaded or seated",
    "The bus driver may do any sequence he or she desires"
]

"Which of the following statements are true about safe following distance between your vehicle and the vehicle in front of you?" = [
    "All options",
    "A two-second following distance may be sufficient in normal conditions for an experienced driver",
    "An inexperienced or beginning driver should maintain at least a three-second following distance under normal driving conditions",
    "At speeds of 40 mph, a four- to five-second following distance is recommended. When road conditions are slippery or the vehicle in front of you blocks your view, a following distance of six or more seconds is recommended."
]

"Passing is prohibited when" = [
    "You are within 100 feet of an intersection or railroad crossing",
    "The vehicle you are following has a slow-moving vehicle symbol",
    "You would be required to pass to the right of a left turning vehicle"
]

"When you are merging onto the freeway or interstate, you should be driving" = [
    "At or near the same speed as the traffic on the freeway or interstate",
    "5 to 10 mph slower than the traffic on the freeway or interstate",
    "The posted speed limit for traffic on the freeway or interstate"
]

"In speed zones of 45 mph or less, you must signal your turn continuously during the last ______feet before turning" = [
    "100 ft",
    "200 ft",
    "300 ft"
]

"In speed zones of 45 mph or more, you must signal your turn continuously during the last ______feet before turning" = [
    "300 ft",
    "200 ft",
    "100 ft"
]

"You should always travel" = [
    "According to road and weather conditions",
    "At the speed of vehicles in front of you",
    "At the speed limit"
]

"When it is raining, you should be most careful when turning or stopping" = [
    "During the first half hour of rain",
    "A half hour after it stops raining",
    "After it has been raining all day"
]

"You are traveling on a two- or three-lane road and meet a stopped school bus with its red lights flashing. You must" = [
    "Stop and remain stopped until the red lights stop flashing and the stop arm is withdrawn",
    "Stop and proceed after a few seconds",
    "Stop only if children are crossing the roadway"
]
[[questions]]
question = "Broken yellow lines (dashes) are used on streets and highways to"
answers = ["Separate lanes of traffic moving in opposite directions"]
alternatives = ["Indicate no passing zones", "Separate lanes of traffic moving in the same direction"]

[[questions]]
question = "Unless a sign is posted, you may turn right at a red light if"
answers = ["You stop and yield to pedestrians and other vehicles before turning"]
alternatives = ["You slow down and proceed with caution", "The street you are turning onto is one-way"]

[[questions]]
question = "Before making a turn, you should"
answers = ["Look to see if other vehicles and/or pedestrians will be in your way"]
alternatives = ["Stop at a crosswalk", "Move slightly to the left when turning right and move slightly to the right when turning left"]

[[questions]]
question = "A flashing red light at an intersection means"
answers = ["Stop and yield the right of way"]
alternatives = ["Stop and wait for the green light", "Slow and go with caution"]

[[questions]]
question = "As your speed increases it is most important to"
answers = ["Increase your following distance"]
alternatives = ["Focus more on the vehicle in front of you", "Decrease your following distance"]

[[questions]]
question = "When driving on gravel or dirt roads"
answers = ["Reduce your speed"]
alternatives = ["Increase your following distance", "Avoid sudden changes in speed or direction"]

[[questions]]
question = "The best way to keep your car from hydroplaning (tires riding on top of water) is"
answers = ["Keep speed down"]
alternatives = ["Make sharp turns", "Brake hard"]

[[questions]]
question = "When you are behind a motorcycle, you should"
answers = ["Allow more following distance"]
alternatives = ["Be ready to use your horn", "Concentrate on the center line"]